name:                ScraperProject
version:             0.1.0.0
github:              "grochowskih/hs-scraper"
license:             BSD3
author:              "HG"
maintainer:          "HG"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ScraperProject#readme>

dependencies:
- base >= 4.7 && < 5
- scalpel
- aeson
- text
- mysql-simple
# - gi-gtk

library:
  source-dirs: src

executables:
  ScraperProject-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ScraperProject

tests:
  ScraperProject-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ScraperProject
